[tool.poetry]
name = "deepsearch"
version = "0.1.0"
description = ""
authors = ["RupeshBansal"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.13"
openai = "^0.28.1"
chromadb = "^0.4.15"
pillow = "10.0.1"
sentence-transformers = "^2.2.2"
torchvision = ">=0.15.1, !=0.15.2"
ftfy = "^6.1.1"
torch = "^2.0.0"
regex = "2023.8.8"
boto3 = "^1.28.72"
openai-whisper = "20230918"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
