[tool.poetry]
name = "infinitesearch"
version = "0.1.0"
description = ""
authors = ["RupeshBansal"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
openai = "^0.28.1"
chromadb = "^0.4.15"
pillow = "^10.1.0"
sentence-transformers = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
